spring.application.name=Checkpoint1

server.port=8085

# Configuracao do banco de dados H2
spring.datasource.url=jdbc:h2:file:~/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Dialeto do H2 para o JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza automaticamente a estrutura do banco com base nas entidades
spring.jpa.hibernate.ddl-auto=update

# Exibe as queries SQL no console
spring.jpa.show-sql=true

# Habilita o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console